# Generated by Django 5.1.1 on 2024-10-11 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='lista',
        ),
        migrations.AddField(
            model_name='site',
            name='lista_ativa',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='lista_ativa', to='wishlist.lista'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='listas',
            field=models.ManyToManyField(to='wishlist.lista'),
        ),
    ]
