# Generated by Django 5.1.1 on 2024-10-10 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lista',
            name='itens',
        ),
        migrations.CreateModel(
            name='ListaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.item')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wishlist.lista')),
            ],
            options={
                'unique_together': {('lista', 'item')},
            },
        ),
    ]
