# Generated by Django 5.1.1 on 2024-10-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0002_remove_lista_itens_listaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='lista',
            name='itens',
            field=models.ManyToManyField(to='wishlist.item'),
        ),
        migrations.DeleteModel(
            name='ListaItem',
        ),
    ]
