# Generated by Django 5.1.1 on 2024-10-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_alter_tipowishlist_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='slug',
        ),
    ]
