# Generated by Django 5.1.1 on 2024-10-10 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0003_lista_itens_delete_listaitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='descricao',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
