# Generated by Django 5.1.1 on 2024-10-13 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0006_site_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='pode_reutilizar',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='site',
            name='lista_ativa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lista_ativa', to='wishlist.lista'),
        ),
    ]
