# Generated by Django 5.1.1 on 2024-10-14 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='data_evento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='descricao_evento',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='horario_evento',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='link_musica',
            field=models.URLField(blank=True, null=True),
        ),
    ]
