# Generated by Django 5.1.1 on 2024-10-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0003_alter_wishlist_creditos_colocados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='link_compra',
            field=models.URLField(blank=True, null=True),
        ),
    ]
