# Generated by Django 5.1.1 on 2024-10-14 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0004_alter_item_link_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade', models.DecimalField(decimal_places=0, max_digits=10)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
