# Generated by Django 5.1.1 on 2024-10-14 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlists', '0005_planocredito'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='itens',
            field=models.ManyToManyField(blank=True, to='wishlists.item'),
        ),
    ]
