# Generated by Django 5.1.1 on 2024-10-12 18:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracoesUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema', models.CharField(choices=[('escuro', 'Escuro'), ('claro', 'Claro')], default='claro', max_length=200)),
                ('notificacoes_itens', models.BooleanField(default=False)),
                ('notificacoes_renovacao', models.BooleanField(default=False)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracoes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
