# Generated by Django 5.1.1 on 2024-10-14 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='creditos',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=10),
        ),
    ]
