# Generated by Django 5.1.1 on 2024-10-14 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_creditos'),
        ('wishlists', '0005_planocredito'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('creditos_movimentados', models.DecimalField(decimal_places=0, max_digits=10)),
                ('is_compra', models.BooleanField(default=False)),
                ('is_debito', models.BooleanField(default=False)),
                ('plano_comprado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wishlists.planocredito')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('wishlist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='wishlists.wishlist')),
            ],
        ),
    ]
